import React, { useEffect, useState } from 'react';
import { addDoc, collection, doc, getDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase';

type FormState = Record<string, string>;
type LinkData = { companyId?: string; title?: string; purpose?: string; status?: string; expiresAt?: string; employeeId?: string; employeeEmail?: string };
const empty: FormState = { firstName: '', lastName: '', email: '', phone: '', dateOfBirth: '', gender: 'Male', address: '', jobTitle: '', employeeCode: '', bankName: '', accountName: '', accountNumber: '', bvn: '', nin: '', taxId: '', pensionPin: '', nhfNumber: '', nhiaNumber: '', nextOfKin: '', relationship: '', emergencyPhone: '', highestQualification: '', medicalNotes: '' };

export default function EmployeeDataPublicForm({ token }: { token: string }) {
  const [link, setLink] = useState<LinkData | null>(null);
  const [form, setForm] = useState<FormState>(empty);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  const [done, setDone] = useState(false);

  useEffect(() => { async function run() { try { const snap = await getDoc(doc(db, 'employee_data_links', token)); if (!snap.exists()) { setMessage('Invalid employee data link.'); return; } const data = snap.data() as LinkData; if (data.status !== 'Active') { setMessage('This link is not active.'); return; } if (data.expiresAt && new Date(data.expiresAt).getTime() < Date.now()) { setMessage('This link has expired.'); return; } setLink(data); setForm({ ...empty, email: data.employeeEmail || '', employeeId: data.employeeId || '' }); } catch (error: any) { setMessage(error.message || String(error)); } finally { setLoading(false); } } run(); }, [token]);
  const setField = (k: string, v: string) => setForm((old) => ({ ...old, [k]: v }));
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!link?.companyId) return; if (!form.firstName || !form.lastName || !form.email) { setMessage('First name, last name and email are required.'); return; } await addDoc(collection(db, 'employee_data_submissions'), { token, companyId: link.companyId, purpose: link.purpose || 'New Employee Data Collection', employeeId: link.employeeId || form.employeeId || '', employeeEmail: form.email, status: 'Pending HR Review', submittedData: form, submittedAt: serverTimestamp() }); setDone(true); }

  if (loading) return <Shell><p className="text-sm font-bold text-slate-600">Loading form...</p></Shell>;
  if (done) return <Shell><Panel><h1 className="text-xl font-black text-slate-900">Submission received</h1><p className="text-sm text-slate-500 mt-2">Your employee details have been submitted to HR for review.</p></Panel></Shell>;
  if (message && !link) return <Shell><Panel><p className="text-sm font-bold text-rose-700">{message}</p></Panel></Shell>;
  return <Shell><form onSubmit={submit} className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 space-y-6"><div><p className="text-[10px] uppercase tracking-[0.2em] text-indigo-600 font-black">PeopleCloudHRIS</p><h1 className="text-xl font-black text-slate-900">{link?.title || 'Employee Data Form'}</h1><p className="text-xs text-slate-500">Submit your details for HR review and employee record update.</p></div>{message && <div className="p-3 rounded-xl bg-amber-50 border border-amber-100 text-xs font-bold text-amber-800">{message}</div>}<Section title="Personal Details"><Field name="First Name" id="firstName" form={form} setField={setField} required /><Field name="Last Name" id="lastName" form={form} setField={setField} required /><Field name="Email" id="email" form={form} setField={setField} required /><Field name="Phone" id="phone" form={form} setField={setField} /><Field name="Date of Birth" id="dateOfBirth" type="date" form={form} setField={setField} /><Field name="Address" id="address" form={form} setField={setField} /></Section><Section title="Employment Details"><Field name="Employee Code" id="employeeCode" form={form} setField={setField} /><Field name="Job Title" id="jobTitle" form={form} setField={setField} /></Section><Section title="Identity, Bank and Statutory Details"><Field name="NIN" id="nin" form={form} setField={setField} /><Field name="BVN" id="bvn" form={form} setField={setField} /><Field name="Tax ID" id="taxId" form={form} setField={setField} /><Field name="Pension PIN" id="pensionPin" form={form} setField={setField} /><Field name="NHF Number" id="nhfNumber" form={form} setField={setField} /><Field name="NHIA Number" id="nhiaNumber" form={form} setField={setField} /><Field name="Bank Name" id="bankName" form={form} setField={setField} /><Field name="Account Name" id="accountName" form={form} setField={setField} /><Field name="Account Number" id="accountNumber" form={form} setField={setField} /></Section><Section title="Emergency and Other Details"><Field name="Next of Kin" id="nextOfKin" form={form} setField={setField} /><Field name="Relationship" id="relationship" form={form} setField={setField} /><Field name="Emergency Phone" id="emergencyPhone" form={form} setField={setField} /><Field name="Highest Qualification" id="highestQualification" form={form} setField={setField} /><Field name="Medical Notes" id="medicalNotes" form={form} setField={setField} /></Section><button type="submit" className="px-5 py-2 bg-slate-900 text-white rounded-xl text-xs font-black">Submit to HR</button></form></Shell>;
}
function Shell({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 p-5 md:p-10"><div className="max-w-5xl mx-auto">{children}</div></div>; }
function Panel({ children }: { children: React.ReactNode }) { return <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-8 text-center">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="text-[11px] uppercase tracking-wider font-black text-slate-800 border-b border-slate-100 pb-2">{title}</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">{children}</div></section>; }
function Field({ name, id, form, setField, type = 'text', required = false }: { name: string; id: string; form: FormState; setField: (k: string, v: string) => void; type?: string; required?: boolean }) { return <div><label className="block text-[10px] uppercase font-black text-slate-500 mb-1">{name}</label><input required={required} type={type} value={form[id] || ''} onChange={(e) => setField(id, e.target.value)} className="w-full px-3 py-2 border border-slate-200 rounded-xl text-xs" /></div>; }
